### ISSUE TITLE
EISDIR when creating quilt files

### ISSUE THREAD

**Issue by hramrach** [openSUSE/rapidquilt#10]
ce7faba2a1026c4f63a4fa4a8241f1d1e06a0e0f in kernel-source
scripts/sequence-patch.sh --dir /dev/shm/quilt --rapid
Creating tree in /dev/shm/quilt/linux-5.3-SLE15-SP3
Cleaning up from previous run
Linking from /dev/shm/quilt/linux-5.3.orig
Applying 41214 patches using 4 threads...
Saving modified files...
Saving rejects to "MAINTAINERS.rej"
Saving quilt backup files (last 100)...
Failed to save quilt backup file: ".pc/patches.suse/nvme-pci-disable-the-write-zeros-command-for-Intel-6.patch/"                                                                  
  Is a directory (os error 21)
[ Tree: /dev/shm/quilt/linux-5.3-SLE15-SP3 ]

**Comment by alesax** [comment]
Regarding this second bug: removing ^+++ lines from changelog of patches.suse/nvme-pci-disable-the-write-zeros-command-for-Intel-6.patch makes the problem disappear.

**Comment by ptesarik** [comment]
This is totally wrong. GNU patch looks for the `---` pattern. It won't be confused by any amount of `+++` or `***`.

**Comment by ptesarik** [comment]
I must correct myself. The logic in GNU patch is much more complex, and it may also parse patches without a `---` line. I'm looking…

**Comment by ptesarik** [comment]
The bug reported by @hanzyd is solved by commit 0121fe373014c51239a33f681eb0960f97073982.

**Comment by ptesarik** [comment]
As of commit bfe437626835d8e745b95193acfe6ece9d8ce905, the original issue is still present:

```
Applying 41214 patches using 4 threads...
Saving modified files...
Saving rejects to "MAINTAINERS.rej"
Saving quilt backup files (last 100)...
Failed to save quilt backup file: ".pc/patches.suse/nvme-pci-disable-the-write-zeros-command-for-Intel-6.patch/"
  Is a directory (os error 21)
```

**Comment by ptesarik** [comment]
I can no longer reproduce the original issue as of commit c993f1a4d252b71ad33bb9bebe8a873dccf6dac3. It must have been fixed as part of the parser rewrite.
